var searchData=
[
  ['postlocalnotification',['PostLocalNotification',['../class_u_t_notifications_1_1_manager.html#a002af5c95f3aa1ea490db8e962d759d4',1,'UTNotifications.Manager.PostLocalNotification(string title, string text, int id, IDictionary&lt; string, string &gt; userData=null, string notificationProfile=null, int badgeNumber=Notification.BADGE_NOT_SPECIFIED, ICollection&lt; Button &gt; buttons=null)'],['../class_u_t_notifications_1_1_manager.html#af70f025962cadc2c7535616b8d0c3bf9',1,'UTNotifications.Manager.PostLocalNotification(LocalNotification notification)']]],
  ['provider',['provider',['../class_u_t_notifications_1_1_push_notification.html#a2ff29719581693df61487700b4e8ccdd',1,'UTNotifications::PushNotification']]],
  ['pushnotification',['PushNotification',['../class_u_t_notifications_1_1_push_notification.html',1,'UTNotifications.PushNotification'],['../class_u_t_notifications_1_1_push_notification.html#a4c486030fd32fb71ba8fefa89d6e591c',1,'UTNotifications.PushNotification.PushNotification(PushNotificationsProvider provider, string title, string text, int id, IDictionary&lt; string, string &gt; userData, string notificationProfile, int badgeNumber, ICollection&lt; Button &gt; buttons)'],['../class_u_t_notifications_1_1_push_notification.html#a941480349f96c1d14645880a67c9a439',1,'UTNotifications.PushNotification.PushNotification(PushNotificationsProvider provider, string title, string text, int id)'],['../class_u_t_notifications_1_1_push_notification.html#ada2b605e228f36a4e4e36c4b9387e9c6',1,'UTNotifications.PushNotification.PushNotification(JSONNode json)']]],
  ['pushnotificationsenabled',['PushNotificationsEnabled',['../class_u_t_notifications_1_1_manager.html#aa4093bcfb69517b3322733a644406cc2',1,'UTNotifications::Manager']]],
  ['pushnotificationsprovider',['PushNotificationsProvider',['../namespace_u_t_notifications.html#ad588ca0e7fad27dd135f91b373136846',1,'UTNotifications']]],
  ['pushnotificator',['PushNotificator',['../classcom_1_1universal__tools_1_1demoserver_1_1_push_notificator.html',1,'com::universal_tools::demoserver']]]
];
