var searchData=
[
  ['schedulenotification',['ScheduleNotification',['../class_u_t_notifications_1_1_manager.html#a53a918379e2495e8b95387d71d668341',1,'UTNotifications.Manager.ScheduleNotification(int triggerInSeconds, string title, string text, int id, IDictionary&lt; string, string &gt; userData=null, string notificationProfile=null, int badgeNumber=-1, ICollection&lt; Button &gt; buttons=null)'],['../class_u_t_notifications_1_1_manager.html#ac69a4c9430aeeaa82abc8795682145c7',1,'UTNotifications.Manager.ScheduleNotification(DateTime triggerDateTime, string title, string text, int id, IDictionary&lt; string, string &gt; userData=null, string notificationProfile=null, int badgeNumber=-1, ICollection&lt; Button &gt; buttons=null)']]],
  ['schedulenotificationrepeating',['ScheduleNotificationRepeating',['../class_u_t_notifications_1_1_manager.html#ac4f1ebdd7f3770bc00df7b932c7254e6',1,'UTNotifications.Manager.ScheduleNotificationRepeating(int firstTriggerInSeconds, int intervalSeconds, string title, string text, int id, IDictionary&lt; string, string &gt; userData=null, string notificationProfile=null, int badgeNumber=-1, ICollection&lt; Button &gt; buttons=null)'],['../class_u_t_notifications_1_1_manager.html#aea61eef156c619ada09184429e9dad78',1,'UTNotifications.Manager.ScheduleNotificationRepeating(DateTime firstTriggerDateTime, int intervalSeconds, string title, string text, int id, IDictionary&lt; string, string &gt; userData=null, string notificationProfile=null, int badgeNumber=-1, ICollection&lt; Button &gt; buttons=null)']]],
  ['sendregistrationid',['SendRegistrationId',['../class_u_t_notifications_1_1_u_t_notifications_sample.html#a2bdc49a77de6237d433996beefb489c5',1,'UTNotifications.UTNotificationsSample.SendRegistrationId(string providerName, string registrationId)'],['../class_u_t_notifications_1_1_u_t_notifications_sample.html#aa60b9dafc1d866fb7941c476232a3157',1,'UTNotifications.UTNotificationsSample.SendRegistrationId(string userId, string providerName, string registrationId)']]],
  ['setbadge',['SetBadge',['../class_u_t_notifications_1_1_manager.html#aae30f6a7c2313ab7044fdeb274fb77c4',1,'UTNotifications::Manager']]],
  ['setnotificationsenabled',['SetNotificationsEnabled',['../class_u_t_notifications_1_1_manager.html#a15099f01700d6abaf17b904ef4d14325',1,'UTNotifications.Manager.SetNotificationsEnabled()'],['../class_u_t_notifications_1_1_u_t_notifications_sample.html#a50da8438662909764e974d91c20e2f48',1,'UTNotifications.UTNotificationsSample.SetNotificationsEnabled()']]],
  ['setpushnotificationsenabled',['SetPushNotificationsEnabled',['../class_u_t_notifications_1_1_manager.html#a8670e0fd2366f8f7271e7d94ca270463',1,'UTNotifications::Manager']]],
  ['showmenu',['ShowMenu',['../class_u_t_notifications_1_1_u_t_notifications_sample.html#ae14a4ffd7a2e470a1271c816f8db8e86',1,'UTNotifications::UTNotificationsSample']]],
  ['showreceivednotification',['ShowReceivedNotification',['../class_u_t_notifications_1_1_u_t_notifications_sample.html#ac5470d651e5498d7d420bacf5735155e',1,'UTNotifications::UTNotificationsSample']]],
  ['start',['Start',['../class_u_t_notifications_1_1_u_t_notifications_sample.html#aea9cf64a8110fe498d8d56d38b767da8',1,'UTNotifications::UTNotificationsSample']]]
];
